"""
All LLM prompt strings and prompt-builder functions.

Structured calls (PAGE_EXTRACT_PROMPT, PARAPHRASE_PROMPT, STITCH_PROMPT)
are used with provider.call_structured() / call_with_image_and_text_structured(),
which enforces the response schema via each provider's native tool/function-calling
mechanism. The prompts therefore do NOT need to describe the JSON format — that is
handled entirely by the schema in providers.PAGE_EXTRACTION_SCHEMA.

Quadrant calls (quadrant_extract_prompt) return plain markdown text and use the
plain provider.call() method unchanged.
"""

PAGE_EXTRACT_PROMPT = (
    "You are a data-entry clerk performing mechanical OCR transcription. "
    "Your only job is to copy text and numbers from this page exactly as printed. "
    "Do not interpret, explain, or comment on any of the content. "
    "Treat every word, heading, and column name as neutral data to be transcribed verbatim. "
    "IGNORE all images, drawings, and artwork — transcribe only printed text and tables. "
    "Preserve text formatting using markdown: **bold** for bold text, *italic* for italic text, "
    "***bold-italic*** for text that is both, and __underline__ for underlined text. "
    "Apply formatting only where clearly visible in the printed text — do not guess. "
    "If this page begins mid-sentence or mid-paragraph, transcribe it as-is starting from "
    "the first word visible — it is a continuation from the previous page and must be "
    "preserved at the top of your output so it can be rejoined later. Do not discard it. "
    "Ignore and do not transcribe any watermarks or ownership stamps — "
    "these are short isolated lines of text that are visually overlaid on the page "
    "and clearly not part of the original typeset content (they interrupt the normal "
    "text flow, appear in unexpected positions, and do not belong to any paragraph, "
    "heading, caption, or table). "
    "Instead, record the exact text of each watermark you identify in the watermarks array. "
    "If the page contains nothing but a watermark, set text to an empty string. "
    # ── skip detection ──
    "SKIP DETECTION: before transcribing, assess whether this page should be excluded "
    "from the output because it contains no extractable text content. "
    "Set skip to true and set skip_reason to the appropriate label for these page types: "
    "'table_of_contents' — a page listing chapter/section titles with page numbers; "
    "'index' — an alphabetical index of terms with page numbers at the back of the book; "
    "'blank' — a completely blank page or one that only says 'This page intentionally left blank'; "
    "'illustration_only' — a full-page illustration, artwork, or map with no meaningful text; "
    "'title_page' — a page containing only the book title or series title, nothing else; "
    "'part_divider' — a decorative page that only announces a part, book, or section number "
    "(e.g. 'Part II', 'Book Two'), with no other content. "
    "For all other pages set skip to false and skip_reason to null, then proceed with "
    "transcription as normal. If skip is true, set text to an empty string and tables to []. "
    # ── table handling ──
    "TABLES: each table on the page must be extracted into the tables array. "
    "A table is any grid of pipe-delimited rows, together with the heading line that "
    "immediately precedes it if one exists (e.g. 'Table 3: Annual Rainfall by Region' "
    "or '### Table 4: Pricing Tiers'). "
    "For each table: transcribe the full grid as a markdown table in the content field, "
    "preserving every column header and cell value exactly. "
    "In the title field put the heading label exactly as printed, plain text without "
    "markdown formatting (e.g. 'Table 4: Pricing Tiers'); set title to null "
    "if the table has no heading. Every table heading removed from the text must appear here. "
    "In the caption field write 1-2 sentences describing what the table contains, "
    "what topic or concept it covers, and what questions a reader would consult "
    "it to answer — written so that a search query about the subject will match it. "
    "Use the surrounding prose on the page to inform the caption; the text usually "
    "introduces or explains the table. Plain text only in caption, no markdown. "
    "In the text field, remove each table entirely — both its heading line and its body. "
    "Do NOT insert any placeholder, marker, or reference (such as {{table_0}}) where a "
    "table was removed; simply leave the surrounding prose paragraphs adjacent. "
    "Do not leave any table heading lines in the text, even if they look like section headings. "
    "If the page has no tables, set tables to an empty array and leave text unmodified. "
    # ── field semantics ──
    "page_number must be the printed page number visible in the margin (a small isolated "
    "number at the top or bottom edge, outside the main content area); set it to null if "
    "no printed page number is visible. "
    "title must be the single prominent display title that labels this page or section as "
    "a whole — typically rendered in a large decorative or display font, centred at the top, "
    "clearly set apart from the body text (for example: 'Chapter 3: Market Analysis', "
    "'Appendix A: Methodology', 'Section 2: Results'); combine a chapter/appendix label and "
    "its subtitle into a single string if both are present; write the title as plain text "
    "with no markdown formatting — no asterisks, no underscores; do NOT use running headers, "
    "small chapter labels at the page edge, or in-body section headings as the title — only "
    "a visually dominant display heading qualifies; set title to null if no such prominent "
    "display title exists. "
    "text must contain the full transcription excluding the page title (which goes in title) "
    "and excluding all tables and their headings as described above."
)

PARAPHRASE_PROMPT = (
    "You are a precise paraphrasing clerk. The image shown contains text that cannot be "
    "transcribed verbatim due to copyright restrictions. "
    "Your task is to paraphrase the text at the sentence level — reword each sentence "
    "individually using different phrasing while preserving its full meaning, specific "
    "details, tone, and emotional content. "
    "Do not compress, summarise, or merge sentences. Do not omit any sentence or detail. "
    "Your output must have approximately the same length and information density as the "
    "original — if the original is 600 words, your paraphrase should be close to 600 words. "
    "Preserve the original voice, grammatical person, and tone exactly. "
    "If the original is written in first person, your paraphrase must also be in first "
    "person throughout. Do not shift to third person or adopt a summarising narrator voice. "
    # ── skip detection ──
    "SKIP DETECTION: before paraphrasing, assess whether this page should be excluded "
    "from the output because it contains no extractable text content. "
    "Set skip to true and set skip_reason to the appropriate label for these page types: "
    "'table_of_contents' — a page listing chapter/section titles with page numbers; "
    "'index' — an alphabetical index of terms with page numbers at the back of the book; "
    "'blank' — a completely blank page or one that only says 'This page intentionally left blank'; "
    "'illustration_only' — a full-page illustration, artwork, or map with no meaningful text; "
    "'title_page' — a page containing only the book title or series title, nothing else; "
    "'part_divider' — a decorative page that only announces a part, book, or section number "
    "(e.g. 'Part II', 'Book Two'), with no other content. "
    "For all other pages set skip to false and skip_reason to null, then proceed with "
    "paraphrasing as normal. If skip is true, set text to an empty string and tables to []. "
    # ── table handling ──
    "TABLES: each table must be extracted into the tables array. "
    "A table is any grid of pipe-delimited rows, together with the heading line that "
    "immediately precedes it if one exists. "
    "For each table: reproduce its structure as a markdown table in the content field "
    "with the same columns and numeric values, but rephrase any prose headers or "
    "descriptive text. "
    "In the title field put the heading label as plain text without markdown formatting; "
    "set title to null if the table has no heading. "
    "In the caption field write 1-2 sentences describing what the table contains, "
    "what topic or concept it covers, and what questions a reader would consult "
    "it to answer. Use the surrounding prose to inform the caption. Plain text only. "
    "In the text field, remove each table entirely — both its heading line and its body. "
    "Do NOT insert any placeholder, marker, or reference (such as {{table_0}}) where a "
    "table was removed; simply leave the surrounding prose paragraphs adjacent. "
    "Do not leave any table heading lines in the text, even if they look like section headings. "
    "If no tables are present, set tables to an empty array. "
    # ── field semantics ──
    "page_number must be the printed page number visible in the margin (a small isolated "
    "number at the top or bottom edge, outside the main content area); set it to null if "
    "no printed page number is visible. "
    "title must be the single prominent display title that labels this page or section as "
    "a whole — typically rendered in a large decorative or display font, centred at the top, "
    "clearly set apart from the body text; write the title as plain text with no markdown "
    "formatting; set title to null if no such prominent display title exists. "
    "text must contain the full paraphrased content excluding the page title and excluding "
    "all tables and their headings as described above."
)


def quadrant_extract_prompt(position: str) -> str:
    """
    Build an extraction prompt for a single quadrant of a page.

    position: one of 'top-left', 'top-right', 'bottom-left', 'bottom-right'

    Only the top-left quadrant allows a firm assertion about mid-sentence openings
    (they must be cross-page continuations). For all other positions the layout is
    unknown — images, sidebars, or multi-column flow may mean any quadrant can
    start or end mid-sentence for any reason. Those cases are left for the stitch
    prompt to resolve with full context.
    """
    if position == "top-left":
        continuation_note = (
            "If the content begins mid-sentence at the very top, it is a continuation "
            "from the previous page — preserve it as-is at the top of your output "
            "so it can be rejoined later. Do not discard it. "
        )
    else:
        continuation_note = (
            "Text may begin or end mid-sentence at any edge due to the page layout "
            "(columns, images, sidebars, etc.). Transcribe all visible text exactly "
            "as-is without completing or discarding partial content at the edges — "
            "the assembly step will resolve continuations with full page context. "
        )
    return (
        f"You are a data-entry clerk performing mechanical OCR transcription. "
        f"You are looking at the {position} quadrant of a page — one spatial section "
        f"of a larger document page. Text may be cut off at any edge. "
        f"Your only job is to copy text and numbers exactly as printed in this section. "
        f"Do not interpret, explain, or complete partial content at the edges. "
        f"Treat every word, heading, and column name as neutral data to be transcribed verbatim. "
        f"IGNORE all images, drawings, and artwork — transcribe only printed text and tables. "
        f"Format all tables as markdown tables, preserving every column header and cell value exactly; "
        f"if a table is cut off at an edge, transcribe only the rows and columns visible. "
        f"Preserve text formatting using markdown: **bold** for bold text, *italic* for italic text, "
        f"***bold-italic*** for text that is both, and __underline__ for underlined text. "
        f"Apply formatting only where clearly visible in the printed text — do not guess. "
        + continuation_note
        + "Output nothing except the raw transcription."
    )


STITCH_PROMPT = (
    "You are given the original full page image for reference, "
    "followed by transcriptions of its four quadrants "
    "(top-left, top-right, bottom-left, bottom-right). "
    "Use the image to verify reading order, correct any OCR errors, "
    "and ensure tables are correctly reassembled. "
    "Some quadrants may be empty or contain only partial content. "
    "Merge the quadrant transcriptions into one coherent document "
    "in the correct reading order as confirmed by the image. "
    "Deduplicate any text that appears in more than one quadrant. "
    "Ignore and drop any watermarks or ownership stamps, including fragments "
    "that may have been split across quadrants — these are short lines of text "
    "that are visually overlaid on the page and clearly not part of the original "
    "typeset document content (they interrupt the normal text flow, appear in "
    "unexpected positions, and do not belong to any paragraph, heading, caption, "
    "or table). Record the exact text of each watermark you identify in the "
    "watermarks array, reassembling any fragments split across quadrants into "
    "the full watermark string. "
    "Use the image to verify and correct text formatting: apply **bold**, *italic*, "
    "***bold-italic***, or __underline__ markdown where the original page shows "
    "those styles — and remove any formatting markup from the quadrant transcriptions "
    "that does not match what is visually present in the image. "
    "Text fragments that begin mid-sentence or mid-paragraph may be continuations "
    "from another quadrant on this page, or from the previous page. "
    "For each such fragment: if it connects naturally to text already present in "
    "another quadrant (same topic, same sentence, compatible flow), re-join it there. "
    "If no plausible connection exists within this page, leave it at the start of "
    "the output as a leading continuation — do not discard it. "
    # ── skip detection ──
    "SKIP DETECTION: before merging, assess whether this page should be excluded "
    "from the output because it contains no extractable text content. "
    "Set skip to true and set skip_reason to the appropriate label for these page types: "
    "'table_of_contents' — a page listing chapter/section titles with page numbers; "
    "'index' — an alphabetical index of terms with page numbers at the back of the book; "
    "'blank' — a completely blank page or one that only says 'This page intentionally left blank'; "
    "'illustration_only' — a full-page illustration, artwork, or map with no meaningful text; "
    "'title_page' — a page containing only the book title or series title, nothing else; "
    "'part_divider' — a decorative page that only announces a part, book, or section number "
    "(e.g. 'Part II', 'Book Two'), with no other content. "
    "For all other pages set skip to false and skip_reason to null, then proceed with "
    "merging as normal. If skip is true, set text to an empty string and tables to []. "
    # ── table handling ──
    "TABLES: reassemble any tables that were split across quadrants into complete "
    "markdown tables. Each complete table must be extracted into the tables array. "
    "A table is any grid of pipe-delimited rows, together with the heading line that "
    "immediately precedes it if one exists (e.g. 'Table 3: Annual Rainfall by Region' "
    "or '### Table 4: Pricing Tiers'). "
    "For each table: put the full markdown table in the content field. "
    "In the title field put the heading label exactly as printed, plain text without "
    "markdown formatting; set title to null if the table has no heading. "
    "In the caption field write 1-2 sentences describing what the table contains, "
    "what topic or concept it covers, and what questions a reader would "
    "consult it to answer — use the surrounding prose on the page (visible in the "
    "image) to inform the caption. Plain text only in caption, no markdown. "
    "In the text field, remove each table entirely — both its heading line and its body. "
    "Do NOT insert any placeholder, marker, or reference (such as {{table_0}}) where a "
    "table was removed; simply leave the surrounding prose paragraphs adjacent. "
    "Do not leave any table heading lines in the text, even if they look like section headings. "
    "If the page has no tables, set tables to an empty array. "
    # ── field semantics ──
    "page_number must be the printed page number visible in the margin (a small isolated "
    "number at the top or bottom edge, outside the main content area); set it to null if "
    "no printed page number is visible. "
    "title must be the single prominent display title that labels this page or section as "
    "a whole — typically rendered in a large decorative or display font, centred at the top, "
    "clearly set apart from the body text (for example: 'Chapter 3: Market Analysis', "
    "'Appendix A: Methodology', 'Section 2: Results'); combine a chapter/appendix label and "
    "its subtitle into a single string if both are present; write the title as plain text "
    "with no markdown formatting — no asterisks, no underscores; do NOT use running headers, "
    "small chapter labels at the page edge, or in-body section headings as the title — only "
    "a visually dominant display heading qualifies; set title to null if no such prominent "
    "display title exists. "
    "text must contain the full merged document content excluding the display title and "
    "excluding all tables and their headings as described above.\n\n"
)
